#database
POSTGRES_SQL_HOST: localhost
POSTGRES_SQL_USERNAME: postgres
POSTGRES_SQL_PASSWORD: Zagzagzag
POSTGRES_SQL_PORT: 5432
POSTGRES_SQL_DB: postgres

#server
SERVER_PORT: 8083
ACTIVE_PROFILE: dev

#email config rfms xyaz exbi ighu
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: mambosag@gmail.com
EMAIL_PASSWORD: rfms xyaz exbi ighu
VERIFY_EMAIL_HOST: http://localhost:${SERVER_PORT}
